-- ================================================================
-- Switch to DEV_USER schema so all objects are owned by DEV_USER
-- not SYS (which would cause ORA-04089 on triggers)
-- ================================================================
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = DEV_USER;

-- ────────────────────────────────────────────
-- TYPES
-- ────────────────────────────────────────────

CREATE OR REPLACE TYPE DEV_USER.T_ADDRESS AS OBJECT (
    STREET      VARCHAR2(200),
    CITY        VARCHAR2(100),
    STATE       VARCHAR2(50),
    ZIP_CODE    VARCHAR2(20),
    COUNTRY     VARCHAR2(100)
);
/

-- ────────────────────────────────────────────
-- SEQUENCES
-- ────────────────────────────────────────────

CREATE SEQUENCE DEV_USER.SEQ_USERS
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE DEV_USER.SEQ_ROLES
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE DEV_USER.SEQ_AUDIT_LOG
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE DEV_USER.SEQ_PRODUCTS
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE DEV_USER.SEQ_ORDERS
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ────────────────────────────────────────────
-- TABLES
-- ────────────────────────────────────────────

CREATE TABLE DEV_USER.ROLES (
    ROLE_ID     NUMBER          DEFAULT DEV_USER.SEQ_ROLES.NEXTVAL  PRIMARY KEY,
    ROLE_NAME   VARCHAR2(50)    NOT NULL,
    DESCRIPTION VARCHAR2(200),
    IS_ACTIVE   NUMBER(1)       DEFAULT 1                           NOT NULL,
    CREATED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP                NOT NULL,
    CONSTRAINT UK_ROLE_NAME  UNIQUE (ROLE_NAME),
    CONSTRAINT CHK_ROLE_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

CREATE TABLE DEV_USER.USERS (
    USER_ID         NUMBER          DEFAULT DEV_USER.SEQ_USERS.NEXTVAL  PRIMARY KEY,
    USERNAME        VARCHAR2(100)   NOT NULL,
    EMAIL           VARCHAR2(255)   NOT NULL,
    PASSWORD_HASH   VARCHAR2(255)   NOT NULL,
    FIRST_NAME      VARCHAR2(100),
    LAST_NAME       VARCHAR2(100),
    ROLE_ID         NUMBER          NOT NULL,
    IS_ACTIVE       NUMBER(1)       DEFAULT 1                           NOT NULL,
    LAST_LOGIN      TIMESTAMP,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP                NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP                NOT NULL,
    CONSTRAINT UK_USERNAME  UNIQUE (USERNAME),
    CONSTRAINT UK_EMAIL     UNIQUE (EMAIL),
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES DEV_USER.ROLES (ROLE_ID),
    CONSTRAINT CHK_USER_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

CREATE TABLE DEV_USER.AUDIT_LOG (
    LOG_ID      NUMBER          DEFAULT DEV_USER.SEQ_AUDIT_LOG.NEXTVAL PRIMARY KEY,
    TABLE_NAME  VARCHAR2(100)   NOT NULL,
    OPERATION   VARCHAR2(10)    NOT NULL,
    RECORD_ID   NUMBER,
    OLD_VALUES  CLOB,
    NEW_VALUES  CLOB,
    CHANGED_BY  VARCHAR2(100),
    CHANGED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP                    NOT NULL,
    CONSTRAINT CHK_AUDIT_OP CHECK (OPERATION IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE TABLE DEV_USER.PRODUCTS (
    PRODUCT_ID    NUMBER          DEFAULT DEV_USER.SEQ_PRODUCTS.NEXTVAL PRIMARY KEY,
    PRODUCT_NAME  VARCHAR2(200)   NOT NULL,
    DESCRIPTION   VARCHAR2(1000),
    PRICE         NUMBER(10, 2)   NOT NULL,
    STOCK_QTY     NUMBER          DEFAULT 0                             NOT NULL,
    IS_ACTIVE     NUMBER(1)       DEFAULT 1                             NOT NULL,
    CREATED_AT    TIMESTAMP       DEFAULT SYSTIMESTAMP                  NOT NULL,
    CONSTRAINT CHK_PRICE       CHECK (PRICE >= 0),
    CONSTRAINT CHK_STOCK       CHECK (STOCK_QTY >= 0),
    CONSTRAINT CHK_PROD_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

CREATE TABLE DEV_USER.ORDERS (
    ORDER_ID      NUMBER          DEFAULT DEV_USER.SEQ_ORDERS.NEXTVAL  PRIMARY KEY,
    USER_ID       NUMBER          NOT NULL,
    PRODUCT_ID    NUMBER          NOT NULL,
    QUANTITY      NUMBER          NOT NULL,
    UNIT_PRICE    NUMBER(10, 2)   NOT NULL,
    TOTAL_AMOUNT  NUMBER(10, 2)   GENERATED ALWAYS AS (QUANTITY * UNIT_PRICE) VIRTUAL,
    STATUS        VARCHAR2(20)    DEFAULT 'PENDING'                     NOT NULL,
    ORDER_DATE    TIMESTAMP       DEFAULT SYSTIMESTAMP                  NOT NULL,
    CONSTRAINT FK_ORDER_USER    FOREIGN KEY (USER_ID)    REFERENCES DEV_USER.USERS (USER_ID),
    CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES DEV_USER.PRODUCTS (PRODUCT_ID),
    CONSTRAINT CHK_QTY          CHECK (QUANTITY > 0),
    CONSTRAINT CHK_ORDER_STATUS CHECK (STATUS IN ('PENDING','CONFIRMED','SHIPPED','DELIVERED','CANCELLED'))
);

-- ────────────────────────────────────────────
-- INDEXES
-- ────────────────────────────────────────────

CREATE INDEX DEV_USER.IDX_USERS_EMAIL    ON DEV_USER.USERS (EMAIL);
CREATE INDEX DEV_USER.IDX_USERS_ROLE     ON DEV_USER.USERS (ROLE_ID);
CREATE INDEX DEV_USER.IDX_USERS_ACTIVE   ON DEV_USER.USERS (IS_ACTIVE);
CREATE INDEX DEV_USER.IDX_ORDERS_USER    ON DEV_USER.ORDERS (USER_ID);
CREATE INDEX DEV_USER.IDX_ORDERS_PRODUCT ON DEV_USER.ORDERS (PRODUCT_ID);
CREATE INDEX DEV_USER.IDX_ORDERS_STATUS  ON DEV_USER.ORDERS (STATUS);
CREATE INDEX DEV_USER.IDX_AUDIT_TABLE    ON DEV_USER.AUDIT_LOG (TABLE_NAME, CHANGED_AT);

-- ────────────────────────────────────────────
-- VIEW
-- ────────────────────────────────────────────

CREATE OR REPLACE VIEW DEV_USER.VW_USER_ORDER_SUMMARY AS
    SELECT
        U.USER_ID,
        U.USERNAME,
        U.EMAIL,
        R.ROLE_NAME,
        COUNT(O.ORDER_ID)   AS TOTAL_ORDERS,
        SUM(O.TOTAL_AMOUNT) AS TOTAL_SPENT,
        MAX(O.ORDER_DATE)   AS LAST_ORDER_DATE
    FROM DEV_USER.USERS U
    JOIN DEV_USER.ROLES  R ON R.ROLE_ID = U.ROLE_ID
    LEFT JOIN DEV_USER.ORDERS O ON O.USER_ID = U.USER_ID
    GROUP BY U.USER_ID, U.USERNAME, U.EMAIL, R.ROLE_NAME;

-- ────────────────────────────────────────────
-- FUNCTIONS
-- ────────────────────────────────────────────

CREATE OR REPLACE FUNCTION DEV_USER.FN_GET_FULL_NAME (
    P_USER_ID IN NUMBER
) RETURN VARCHAR2
IS
    V_FULL_NAME VARCHAR2(210);
BEGIN
    SELECT
        CASE
            WHEN FIRST_NAME IS NOT NULL AND LAST_NAME IS NOT NULL THEN FIRST_NAME || ' ' || LAST_NAME
            WHEN FIRST_NAME IS NOT NULL THEN FIRST_NAME
            ELSE USERNAME
        END
    INTO V_FULL_NAME
    FROM DEV_USER.USERS
    WHERE USER_ID = P_USER_ID;

    RETURN V_FULL_NAME;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN NULL;
END FN_GET_FULL_NAME;
/

CREATE OR REPLACE FUNCTION DEV_USER.FN_GET_USER_TOTAL_SPEND (
    P_USER_ID IN NUMBER
) RETURN NUMBER
IS
    V_TOTAL NUMBER := 0;
BEGIN
    SELECT NVL(SUM(TOTAL_AMOUNT), 0)
    INTO V_TOTAL
    FROM DEV_USER.ORDERS
    WHERE USER_ID = P_USER_ID
      AND STATUS != 'CANCELLED';

    RETURN V_TOTAL;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END FN_GET_USER_TOTAL_SPEND;
/

-- ────────────────────────────────────────────
-- STORED PROCEDURES
-- ────────────────────────────────────────────

CREATE OR REPLACE PROCEDURE DEV_USER.SP_CREATE_USER (
    P_USERNAME      IN  VARCHAR2,
    P_EMAIL         IN  VARCHAR2,
    P_PASSWORD_HASH IN  VARCHAR2,
    P_FIRST_NAME    IN  VARCHAR2 DEFAULT NULL,
    P_LAST_NAME     IN  VARCHAR2 DEFAULT NULL,
    P_ROLE_ID       IN  NUMBER   DEFAULT 2,
    P_USER_ID       OUT NUMBER
)
IS
BEGIN
    INSERT INTO DEV_USER.USERS (
        USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, ROLE_ID
    ) VALUES (
        P_USERNAME, P_EMAIL, P_PASSWORD_HASH, P_FIRST_NAME, P_LAST_NAME, P_ROLE_ID
    )
    RETURNING USER_ID INTO P_USER_ID;
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Username or Email already exists: ' || P_USERNAME);
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20099, 'SP_CREATE_USER failed: ' || SQLERRM);
END SP_CREATE_USER;
/

CREATE OR REPLACE PROCEDURE DEV_USER.SP_DEACTIVATE_USER (
    P_USER_ID IN NUMBER
)
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM DEV_USER.USERS WHERE USER_ID = P_USER_ID;

    IF V_COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'User not found: ' || P_USER_ID);
    END IF;

    UPDATE DEV_USER.USERS
    SET IS_ACTIVE  = 0,
        UPDATED_AT = SYSTIMESTAMP
    WHERE USER_ID = P_USER_ID;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20099, 'SP_DEACTIVATE_USER failed: ' || SQLERRM);
END SP_DEACTIVATE_USER;
/

CREATE OR REPLACE PROCEDURE DEV_USER.SP_PLACE_ORDER (
    P_USER_ID    IN  NUMBER,
    P_PRODUCT_ID IN  NUMBER,
    P_QUANTITY   IN  NUMBER,
    P_ORDER_ID   OUT NUMBER
)
IS
    V_PRICE  NUMBER;
    V_STOCK  NUMBER;
BEGIN
    SELECT PRICE, STOCK_QTY
    INTO V_PRICE, V_STOCK
    FROM DEV_USER.PRODUCTS
    WHERE PRODUCT_ID = P_PRODUCT_ID AND IS_ACTIVE = 1;

    IF V_STOCK < P_QUANTITY THEN
        RAISE_APPLICATION_ERROR(-20003, 'Insufficient stock for product: ' || P_PRODUCT_ID);
    END IF;

    INSERT INTO DEV_USER.ORDERS (USER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE)
    VALUES (P_USER_ID, P_PRODUCT_ID, P_QUANTITY, V_PRICE)
    RETURNING ORDER_ID INTO P_ORDER_ID;

    UPDATE DEV_USER.PRODUCTS
    SET STOCK_QTY = STOCK_QTY - P_QUANTITY
    WHERE PRODUCT_ID = P_PRODUCT_ID;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20004, 'Product not found or inactive: ' || P_PRODUCT_ID);
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20099, 'SP_PLACE_ORDER failed: ' || SQLERRM);
END SP_PLACE_ORDER;
/

-- ────────────────────────────────────────────
-- TRIGGER
-- ✅ Owned by DEV_USER (not SYS) — fixes ORA-04089
-- ────────────────────────────────────────────

CREATE OR REPLACE TRIGGER DEV_USER.TRG_USERS_AUDIT
    AFTER INSERT OR UPDATE OR DELETE ON DEV_USER.USERS
    FOR EACH ROW
DECLARE
    V_OPERATION VARCHAR2(10);
    V_OLD_VAL   CLOB;
    V_NEW_VAL   CLOB;
BEGIN
    IF INSERTING THEN
        V_OPERATION := 'INSERT';
        V_NEW_VAL   := '{"username":"' || :NEW.USERNAME || '","email":"' || :NEW.EMAIL || '","role_id":' || :NEW.ROLE_ID || '}';
    ELSIF UPDATING THEN
        V_OPERATION := 'UPDATE';
        V_OLD_VAL   := '{"username":"' || :OLD.USERNAME || '","email":"' || :OLD.EMAIL || '","is_active":' || :OLD.IS_ACTIVE || '}';
        V_NEW_VAL   := '{"username":"' || :NEW.USERNAME || '","email":"' || :NEW.EMAIL || '","is_active":' || :NEW.IS_ACTIVE || '}';
    ELSE
        V_OPERATION := 'DELETE';
        V_OLD_VAL   := '{"username":"' || :OLD.USERNAME || '","email":"' || :OLD.EMAIL || '}';
    END IF;

    INSERT INTO DEV_USER.AUDIT_LOG (
        TABLE_NAME, OPERATION, RECORD_ID, OLD_VALUES, NEW_VALUES, CHANGED_BY
    ) VALUES (
        'USERS', V_OPERATION,
        COALESCE(:NEW.USER_ID, :OLD.USER_ID),
        V_OLD_VAL, V_NEW_VAL,
        SYS_CONTEXT('USERENV', 'SESSION_USER')
    );
END TRG_USERS_AUDIT;
/

-- ────────────────────────────────────────────
-- SEED DATA
-- ────────────────────────────────────────────

INSERT INTO DEV_USER.ROLES (ROLE_NAME, DESCRIPTION)
    VALUES ('ADMIN', 'Full system access');
INSERT INTO DEV_USER.ROLES (ROLE_NAME, DESCRIPTION)
    VALUES ('USER', 'Standard user access');
INSERT INTO DEV_USER.ROLES (ROLE_NAME, DESCRIPTION)
    VALUES ('MANAGER', 'Manager level access');
INSERT INTO DEV_USER.ROLES (ROLE_NAME, IS_ACTIVE, DESCRIPTION)
    VALUES ('GUEST', 0, 'Inactive guest role');

INSERT INTO DEV_USER.USERS (USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, ROLE_ID)
    VALUES ('admin',    'admin@example.com',   '$2a$10$dummyHashForDevOnly.admin000', 'Alice', 'Admin',   1);
INSERT INTO DEV_USER.USERS (USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, ROLE_ID)
    VALUES ('jdoe',     'jdoe@example.com',    '$2a$10$dummyHashForDevOnly.jdoe000',  'John',  'Doe',     2);
INSERT INTO DEV_USER.USERS (USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, ROLE_ID)
    VALUES ('jsmith',   'jsmith@example.com',  '$2a$10$dummyHashForDevOnly.jsmith00', 'Jane',  'Smith',   2);
INSERT INTO DEV_USER.USERS (USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, ROLE_ID)
    VALUES ('manager1', 'manager@example.com', '$2a$10$dummyHashForDevOnly.mgr0000',  'Bob',   'Manager', 3);

INSERT INTO DEV_USER.PRODUCTS (PRODUCT_NAME, DESCRIPTION, PRICE, STOCK_QTY)
    VALUES ('Laptop Pro 15',  'High performance laptop',   1299.99, 50);
INSERT INTO DEV_USER.PRODUCTS (PRODUCT_NAME, DESCRIPTION, PRICE, STOCK_QTY)
    VALUES ('Wireless Mouse', 'Ergonomic wireless mouse',    29.99, 200);
INSERT INTO DEV_USER.PRODUCTS (PRODUCT_NAME, DESCRIPTION, PRICE, STOCK_QTY)
    VALUES ('USB-C Hub',      '7-in-1 USB-C hub',            49.99, 150);
INSERT INTO DEV_USER.PRODUCTS (PRODUCT_NAME, DESCRIPTION, PRICE, STOCK_QTY)
    VALUES ('Monitor 27"',   '4K IPS display',             399.99, 30);

INSERT INTO DEV_USER.ORDERS (USER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS)
    VALUES (2, 1, 1, 1299.99, 'DELIVERED');
INSERT INTO DEV_USER.ORDERS (USER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS)
    VALUES (2, 2, 2,   29.99, 'SHIPPED');
INSERT INTO DEV_USER.ORDERS (USER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS)
    VALUES (3, 3, 1,   49.99, 'PENDING');
INSERT INTO DEV_USER.ORDERS (USER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE, STATUS)
    VALUES (4, 4, 2,  399.99, 'CONFIRMED');

COMMIT;