CREATE OR REPLACE EDITIONABLE FUNCTION "FN_GET_USER_TOTAL_SPEND" (
    P_USER_ID IN NUMBER
) RETURN NUMBER
IS
    V_TOTAL NUMBER := 0;
BEGIN
    SELECT NVL(SUM(TOTAL_AMOUNT), 0)
    INTO V_TOTAL
    FROM ORDERS
    WHERE USER_ID = P_USER_ID
      AND STATUS != 'CANCELLED';

    RETURN V_TOTAL;
EXCEPTION
    WHEN OTHERS THEN RETURN 0;
END FN_GET_USER_TOTAL_SPEND;
/
