CREATE OR REPLACE EDITIONABLE FUNCTION "FN_GET_FULL_NAME" (
    P_USER_ID IN NUMBER
) RETURN VARCHAR2
IS
    V_FULL_NAME VARCHAR2(210);
BEGIN
    SELECT
        CASE
            WHEN FIRST_NAME IS NOT NULL AND LAST_NAME IS NOT NULL THEN FIRST_NAME || ' ' || LAST_NAME
            WHEN FIRST_NAME IS NOT NULL THEN FIRST_NAME
            ELSE USERNAME
        END
    INTO V_FULL_NAME
    FROM USERS
    WHERE USER_ID = P_USER_ID;

    RETURN V_FULL_NAME;
EXCEPTION
    WHEN NO_DATA_FOUND THEN RETURN NULL;
END FN_GET_FULL_NAME;
/
