CREATE OR REPLACE EDITIONABLE PROCEDURE "SP_PLACE_ORDER" (
    P_USER_ID    IN  NUMBER,
    P_PRODUCT_ID IN  NUMBER,
    P_QUANTITY   IN  NUMBER,
    P_ORDER_ID   OUT NUMBER
)
IS
    V_PRICE  NUMBER;
    V_STOCK  NUMBER;
BEGIN
    SELECT PRICE, STOCK_QTY
    INTO V_PRICE, V_STOCK
    FROM PRODUCTS
    WHERE PRODUCT_ID = P_PRODUCT_ID AND IS_ACTIVE = 1;

    IF V_STOCK < P_QUANTITY THEN
        RAISE_APPLICATION_ERROR(-20003, 'Insufficient stock for product: ' || P_PRODUCT_ID);
    END IF;

    INSERT INTO ORDERS (USER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE)
    VALUES (P_USER_ID, P_PRODUCT_ID, P_QUANTITY, V_PRICE)
    RETURNING ORDER_ID INTO P_ORDER_ID;

    UPDATE PRODUCTS
    SET STOCK_QTY = STOCK_QTY - P_QUANTITY
    WHERE PRODUCT_ID = P_PRODUCT_ID;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20004, 'Product not found or inactive: ' || P_PRODUCT_ID);
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20099, 'SP_PLACE_ORDER failed: ' || SQLERRM);
END SP_PLACE_ORDER;
/
