CREATE OR REPLACE EDITIONABLE PROCEDURE "SP_CREATE_USER" (
    P_USERNAME      IN  VARCHAR2,
    P_EMAIL         IN  VARCHAR2,
    P_PASSWORD_HASH IN  VARCHAR2,
    P_FIRST_NAME    IN  VARCHAR2 DEFAULT NULL,
    P_LAST_NAME     IN  VARCHAR2 DEFAULT NULL,
    P_ROLE_ID       IN  NUMBER   DEFAULT 2,
    P_USER_ID       OUT NUMBER
)
IS
BEGIN
    INSERT INTO USERS (
        USERNAME, EMAIL, PASSWORD_HASH, FIRST_NAME, LAST_NAME, ROLE_ID
    ) VALUES (
        P_USERNAME, P_EMAIL, P_PASSWORD_HASH, P_FIRST_NAME, P_LAST_NAME, P_ROLE_ID
    )
    RETURNING USER_ID INTO P_USER_ID;
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        RAISE_APPLICATION_ERROR(-20001, 'Username or Email already exists: ' || P_USERNAME);
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20099, 'SP_CREATE_USER failed: ' || SQLERRM);
END SP_CREATE_USER;
/
