CREATE OR REPLACE EDITIONABLE PROCEDURE "SP_DEACTIVATE_USER" (
    P_USER_ID IN NUMBER
)
IS
    V_COUNT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_COUNT FROM USERS WHERE USER_ID = P_USER_ID;

    IF V_COUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'User not found: ' || P_USER_ID);
    END IF;

    UPDATE USERS
    SET IS_ACTIVE  = 0,
        UPDATED_AT = SYSTIMESTAMP
    WHERE USER_ID = P_USER_ID;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20099, 'SP_DEACTIVATE_USER failed: ' || SQLERRM);
END SP_DEACTIVATE_USER;
/
