CREATE OR REPLACE EDITIONABLE TYPE "T_ADDRESS" AS OBJECT (
    STREET      VARCHAR2(200),
    CITY        VARCHAR2(100),
    STATE       VARCHAR2(50),
    ZIP_CODE    VARCHAR2(20),
    COUNTRY     VARCHAR2(100)
);
/
