-- ================================================================
-- Switch to XEPDB1 before granting — LOCAL_USER lives there, not CDB
-- ================================================================
ALTER SESSION SET CONTAINER = XEPDB1;
-- Grants for LOCAL_USER
GRANT CREATE SESSION          TO LOCAL_USER;
GRANT CREATE TABLE            TO LOCAL_USER;
GRANT CREATE VIEW             TO LOCAL_USER;
GRANT CREATE SEQUENCE         TO LOCAL_USER;
GRANT CREATE PROCEDURE        TO LOCAL_USER;
GRANT CREATE TRIGGER          TO LOCAL_USER;
GRANT CREATE TYPE             TO LOCAL_USER;
GRANT UNLIMITED TABLESPACE    TO LOCAL_USER;
GRANT EXECUTE ON DBMS_METADATA TO LOCAL_USER;
GRANT SELECT ON SYS.DBA_OBJECTS TO LOCAL_USER;
GRANT SELECT ON SYS.DBA_SOURCE  TO LOCAL_USER;